controller_manager:
  ros__parameters:
    update_rate: 30
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - pan_joint
      - tilt_joint
    interface_name: position
